2015-10-23 00:14:54 Error: [Cake\View\Exception\MissingTemplateException] Template file "Articles\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'Articles\\index.ctp',
)
Request URL: /cake/articles
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\View\View.php(575): Cake\View\View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Controller\Controller.php(611): Cake\View\View->render(NULL, NULL)
#2 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(120): Cake\Controller\Controller->render()
#3 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\ArticlesController))
#4 C:\xampp\htdocs\cake\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#5 {main}


2015-10-23 00:15:27 Error: [Cake\Controller\Exception\MissingActionException] Action ArticlesController::view() could not be found, or is not accessible.
Exception Attributes: array (
  'controller' => 'ArticlesController',
  'action' => 'view',
  'prefix' => '',
  'plugin' => NULL,
)
Request URL: /cake/articles/view/1
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#1 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\ArticlesController))
#2 C:\xampp\htdocs\cake\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 {main}


2015-10-23 00:17:07 Error: [Cake\Controller\Exception\MissingActionException] Action ArticlesController::view() could not be found, or is not accessible.
Exception Attributes: array (
  'controller' => 'ArticlesController',
  'action' => 'view',
  'prefix' => '',
  'plugin' => NULL,
)
Request URL: /cake/articles/view/3
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#1 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\ArticlesController))
#2 C:\xampp\htdocs\cake\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 {main}


2015-10-23 00:17:11 Error: [Cake\Controller\Exception\MissingActionException] Action ArticlesController::view() could not be found, or is not accessible.
Exception Attributes: array (
  'controller' => 'ArticlesController',
  'action' => 'view',
  'prefix' => '',
  'plugin' => NULL,
)
Request URL: /cake/articles/view/2
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#1 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\ArticlesController))
#2 C:\xampp\htdocs\cake\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 {main}


2015-10-23 00:21:53 Error: [Cake\Controller\Exception\MissingActionException] Action ArticlesController::view() could not be found, or is not accessible.
Exception Attributes: array (
  'controller' => 'ArticlesController',
  'action' => 'view',
  'prefix' => '',
  'plugin' => NULL,
)
Request URL: /cake/articles/view/1
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#1 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\ArticlesController))
#2 C:\xampp\htdocs\cake\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 {main}


2015-10-23 00:21:57 Error: [Cake\Controller\Exception\MissingActionException] Action ArticlesController::view() could not be found, or is not accessible.
Exception Attributes: array (
  'controller' => 'ArticlesController',
  'action' => 'view',
  'prefix' => '',
  'plugin' => NULL,
)
Request URL: /cake/articles/view/2
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#1 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\ArticlesController))
#2 C:\xampp\htdocs\cake\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 {main}


2015-10-23 00:22:00 Error: [Cake\Controller\Exception\MissingActionException] Action ArticlesController::view() could not be found, or is not accessible.
Exception Attributes: array (
  'controller' => 'ArticlesController',
  'action' => 'view',
  'prefix' => '',
  'plugin' => NULL,
)
Request URL: /cake/articles/view/3
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#1 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\ArticlesController))
#2 C:\xampp\htdocs\cake\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 {main}


2015-10-23 00:22:21 Error: [Cake\Controller\Exception\MissingActionException] Action ArticlesController::view() could not be found, or is not accessible.
Exception Attributes: array (
  'controller' => 'ArticlesController',
  'action' => 'view',
  'prefix' => '',
  'plugin' => NULL,
)
Request URL: /cake/articles/view
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#1 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\ArticlesController))
#2 C:\xampp\htdocs\cake\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 {main}


2015-10-23 00:23:35 Error: [Cake\Controller\Exception\MissingActionException] Action ArticlesController::view() could not be found, or is not accessible.
Exception Attributes: array (
  'controller' => 'ArticlesController',
  'action' => 'view',
  'prefix' => '',
  'plugin' => NULL,
)
Request URL: /cake/articles/view/1
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#1 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\ArticlesController))
#2 C:\xampp\htdocs\cake\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 {main}


2015-10-23 00:27:15 Error: Fatal Error (4): syntax error, unexpected 'public' (T_PUBLIC) in [C:\xampp\htdocs\cake\src\Controller\ArticlesController.php, line 18]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-10-23 00:27:16 Error: [Cake\Error\FatalErrorException] syntax error, unexpected 'public' (T_PUBLIC)
Request URL: /cake/articles/view/1
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 18)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-10-23 00:27:23 Error: Fatal Error (4): syntax error, unexpected 'public' (T_PUBLIC) in [C:\xampp\htdocs\cake\src\Controller\ArticlesController.php, line 18]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-10-23 00:27:23 Error: [Cake\Error\FatalErrorException] syntax error, unexpected 'public' (T_PUBLIC)
Request URL: /cake/articles/view/1
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 18)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-10-23 00:27:35 Error: Fatal Error (4): syntax error, unexpected 'public' (T_PUBLIC) in [C:\xampp\htdocs\cake\src\Controller\ArticlesController.php, line 18]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-10-23 00:27:36 Error: [Cake\Error\FatalErrorException] syntax error, unexpected 'public' (T_PUBLIC)
Request URL: /cake/articles/view/2
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 18)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-10-23 00:51:10 Error: Fatal Error (4): syntax error, unexpected 'public' (T_PUBLIC) in [C:\xampp\htdocs\cake\src\Controller\ArticlesController.php, line 38]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-10-23 00:51:10 Error: [Cake\Error\FatalErrorException] syntax error, unexpected 'public' (T_PUBLIC)
Request URL: /cake/articles
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 38)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-10-29 18:37:25 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Add could not be found.
Exception Attributes: array (
  'class' => 'Add',
  'plugin' => NULL,
  'prefix' => NULL,
  '_ext' => NULL,
)
Request URL: /cake/add
Stack Trace:
#0 C:\xampp\htdocs\cake\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#1 {main}


2015-10-29 18:41:43 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Add could not be found.
Exception Attributes: array (
  'class' => 'Add',
  'plugin' => NULL,
  'prefix' => NULL,
  '_ext' => NULL,
)
Request URL: /cake/add
Stack Trace:
#0 C:\xampp\htdocs\cake\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#1 {main}


2015-10-29 18:54:51 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Users could not be found.
Exception Attributes: array (
  'class' => 'Users',
  'plugin' => NULL,
  'prefix' => NULL,
  '_ext' => NULL,
)
Request URL: /cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#1 {main}


2015-10-29 18:55:07 Error: [Cake\View\Exception\MissingTemplateException] Template file "Users\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'Users\\index.ctp',
)
Request URL: /cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\View\View.php(575): Cake\View\View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Controller\Controller.php(611): Cake\View\View->render(NULL, NULL)
#2 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(120): Cake\Controller\Controller->render()
#3 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\UsersController))
#4 C:\xampp\htdocs\cake\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#5 {main}


2015-10-29 18:57:29 Warning: Warning (2): Invalid argument supplied for foreach() in [C:\xampp\htdocs\cake\src\Template\Users\index.ctp, line 12]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 138
include - APP/Template\Users\index.ctp, line 12
Cake\View\View::_evaluate() - CORE\src\View\View.php, line 970
Cake\View\View::_render() - CORE\src\View\View.php, line 930
Cake\View\View::render() - CORE\src\View\View.php, line 578
Cake\Controller\Controller::render() - CORE\src\Controller\Controller.php, line 611
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 120
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-10-29 18:59:51 Error: [Cake\View\Exception\MissingTemplateException] Template file "Users\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'Users\\index.ctp',
)
Request URL: /cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\View\View.php(575): Cake\View\View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Controller\Controller.php(611): Cake\View\View->render(NULL, NULL)
#2 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(120): Cake\Controller\Controller->render()
#3 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\UsersController))
#4 C:\xampp\htdocs\cake\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#5 {main}


2015-10-29 19:08:42 Error: [Cake\View\Exception\MissingTemplateException] Template file "Users\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'Users\\index.ctp',
)
Request URL: /cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\View\View.php(575): Cake\View\View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Controller\Controller.php(611): Cake\View\View->render(NULL, NULL)
#2 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(120): Cake\Controller\Controller->render()
#3 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\UsersController))
#4 C:\xampp\htdocs\cake\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#5 {main}


2015-10-29 19:08:57 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Add could not be found.
Exception Attributes: array (
  'class' => 'Add',
  'plugin' => NULL,
  'prefix' => NULL,
  '_ext' => NULL,
)
Request URL: /cake/add
Stack Trace:
#0 C:\xampp\htdocs\cake\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#1 {main}


2015-10-29 19:09:14 Error: [Cake\Controller\Exception\MissingActionException] Action ArticlesController::user() could not be found, or is not accessible.
Exception Attributes: array (
  'controller' => 'ArticlesController',
  'action' => 'user',
  'prefix' => '',
  'plugin' => NULL,
)
Request URL: /cake/articles/user
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#1 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\ArticlesController))
#2 C:\xampp\htdocs\cake\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 {main}


2015-10-29 19:09:18 Error: [Cake\Controller\Exception\MissingActionException] Action ArticlesController::users() could not be found, or is not accessible.
Exception Attributes: array (
  'controller' => 'ArticlesController',
  'action' => 'users',
  'prefix' => '',
  'plugin' => NULL,
)
Request URL: /cake/articles/users
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#1 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\ArticlesController))
#2 C:\xampp\htdocs\cake\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 {main}


2015-10-29 19:09:29 Error: [Cake\View\Exception\MissingTemplateException] Template file "Users\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'Users\\index.ctp',
)
Request URL: /cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\View\View.php(575): Cake\View\View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Controller\Controller.php(611): Cake\View\View->render(NULL, NULL)
#2 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(120): Cake\Controller\Controller->render()
#3 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\UsersController))
#4 C:\xampp\htdocs\cake\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#5 {main}


2015-10-29 19:12:35 Error: [Cake\Controller\Exception\MissingActionException] Action ArticlesController::users() could not be found, or is not accessible.
Exception Attributes: array (
  'controller' => 'ArticlesController',
  'action' => 'users',
  'prefix' => '',
  'plugin' => NULL,
)
Request URL: /cake/articles/users
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#1 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\ArticlesController))
#2 C:\xampp\htdocs\cake\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 {main}


2015-10-29 19:12:35 Error: [Cake\Controller\Exception\MissingActionException] Action ArticlesController::user() could not be found, or is not accessible.
Exception Attributes: array (
  'controller' => 'ArticlesController',
  'action' => 'user',
  'prefix' => '',
  'plugin' => NULL,
)
Request URL: /cake/articles/user
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#1 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\ArticlesController))
#2 C:\xampp\htdocs\cake\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 {main}


2015-10-29 19:12:35 Error: [Cake\Controller\Exception\MissingActionException] Action ArticlesController::users() could not be found, or is not accessible.
Exception Attributes: array (
  'controller' => 'ArticlesController',
  'action' => 'users',
  'prefix' => '',
  'plugin' => NULL,
)
Request URL: /cake/articles/users
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#1 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\ArticlesController))
#2 C:\xampp\htdocs\cake\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 {main}


2015-10-29 19:12:36 Error: [Cake\Controller\Exception\MissingActionException] Action ArticlesController::users() could not be found, or is not accessible.
Exception Attributes: array (
  'controller' => 'ArticlesController',
  'action' => 'users',
  'prefix' => '',
  'plugin' => NULL,
)
Request URL: /cake/articles/users
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#1 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\ArticlesController))
#2 C:\xampp\htdocs\cake\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 {main}


2015-10-29 19:12:36 Error: [Cake\Controller\Exception\MissingActionException] Action ArticlesController::users() could not be found, or is not accessible.
Exception Attributes: array (
  'controller' => 'ArticlesController',
  'action' => 'users',
  'prefix' => '',
  'plugin' => NULL,
)
Request URL: /cake/articles/users
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#1 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\ArticlesController))
#2 C:\xampp\htdocs\cake\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 {main}


2015-10-29 19:12:37 Error: [Cake\Controller\Exception\MissingActionException] Action ArticlesController::user() could not be found, or is not accessible.
Exception Attributes: array (
  'controller' => 'ArticlesController',
  'action' => 'user',
  'prefix' => '',
  'plugin' => NULL,
)
Request URL: /cake/articles/user
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#1 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\ArticlesController))
#2 C:\xampp\htdocs\cake\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 {main}


2015-10-29 19:12:38 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Add could not be found.
Exception Attributes: array (
  'class' => 'Add',
  'plugin' => NULL,
  'prefix' => NULL,
  '_ext' => NULL,
)
Request URL: /cake/add
Stack Trace:
#0 C:\xampp\htdocs\cake\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#1 {main}


2015-10-29 19:12:39 Error: [Cake\View\Exception\MissingTemplateException] Template file "Users\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'Users\\index.ctp',
)
Request URL: /cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\View\View.php(575): Cake\View\View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Controller\Controller.php(611): Cake\View\View->render(NULL, NULL)
#2 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(120): Cake\Controller\Controller->render()
#3 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\UsersController))
#4 C:\xampp\htdocs\cake\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#5 {main}


2015-10-29 19:12:49 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Login could not be found.
Exception Attributes: array (
  'class' => 'Login',
  'plugin' => NULL,
  'prefix' => NULL,
  '_ext' => NULL,
)
Request URL: /cake/login
Stack Trace:
#0 C:\xampp\htdocs\cake\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#1 {main}


2015-10-29 19:13:18 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Login could not be found.
Exception Attributes: array (
  'class' => 'Login',
  'plugin' => NULL,
  'prefix' => NULL,
  '_ext' => NULL,
)
Request URL: /cake/login
Stack Trace:
#0 C:\xampp\htdocs\cake\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#1 {main}


2015-10-29 19:13:26 Error: [Cake\View\Exception\MissingTemplateException] Template file "Users\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'Users\\index.ctp',
)
Request URL: /cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\View\View.php(575): Cake\View\View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Controller\Controller.php(611): Cake\View\View->render(NULL, NULL)
#2 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(120): Cake\Controller\Controller->render()
#3 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\UsersController))
#4 C:\xampp\htdocs\cake\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#5 {main}


2015-10-29 19:13:27 Error: [Cake\View\Exception\MissingTemplateException] Template file "Users\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'Users\\index.ctp',
)
Request URL: /cake/users
Stack Trace:
#0 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\View\View.php(575): Cake\View\View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Controller\Controller.php(611): Cake\View\View->render(NULL, NULL)
#2 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(120): Cake\Controller\Controller->render()
#3 C:\xampp\htdocs\cake\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\UsersController))
#4 C:\xampp\htdocs\cake\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#5 {main}


2015-11-11 03:35:03 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Index could not be found.
Exception Attributes: array (
  'class' => 'Index',
  'plugin' => NULL,
  'prefix' => NULL,
  '_ext' => NULL,
)
Request URL: /cakephp/index
Stack Trace:
#0 C:\xampp\htdocs\cakephp\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#1 {main}


2015-11-11 03:35:48 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Orders could not be found.
Exception Attributes: array (
  'class' => 'Orders',
  'plugin' => NULL,
  'prefix' => NULL,
  '_ext' => NULL,
)
Request URL: /cakephp/orders
Stack Trace:
#0 C:\xampp\htdocs\cakephp\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#1 {main}


2015-11-11 03:37:03 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Orders could not be found.
Exception Attributes: array (
  'class' => 'Orders',
  'plugin' => NULL,
  'prefix' => NULL,
  '_ext' => NULL,
)
Request URL: /cakephp/orders
Stack Trace:
#0 C:\xampp\htdocs\cakephp\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#1 {main}


2015-11-11 03:38:00 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Orders could not be found.
Exception Attributes: array (
  'class' => 'Orders',
  'plugin' => NULL,
  'prefix' => NULL,
  '_ext' => NULL,
)
Request URL: /cakephp/orders
Stack Trace:
#0 C:\xampp\htdocs\cakephp\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#1 {main}


2015-11-11 03:38:27 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Orders could not be found.
Exception Attributes: array (
  'class' => 'Orders',
  'plugin' => NULL,
  'prefix' => NULL,
  '_ext' => NULL,
)
Request URL: /cakephp/orders
Stack Trace:
#0 C:\xampp\htdocs\cakephp\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#1 {main}


2015-11-11 03:39:05 Warning: Warning (2): Invalid argument supplied for foreach() in [C:\xampp\htdocs\cakephp\src\Template\Orders\index.ctp, line 13]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 138
include - APP/Template\Orders\index.ctp, line 13
Cake\View\View::_evaluate() - CORE\src\View\View.php, line 970
Cake\View\View::_render() - CORE\src\View\View.php, line 930
Cake\View\View::render() - CORE\src\View\View.php, line 578
Cake\Controller\Controller::render() - CORE\src\Controller\Controller.php, line 611
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 120
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-11-11 03:41:15 Warning: Warning (2): Invalid argument supplied for foreach() in [C:\xampp\htdocs\cakephp\src\Template\Orders\index.ctp, line 13]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 138
include - APP/Template\Orders\index.ctp, line 13
Cake\View\View::_evaluate() - CORE\src\View\View.php, line 970
Cake\View\View::_render() - CORE\src\View\View.php, line 930
Cake\View\View::render() - CORE\src\View\View.php, line 578
Cake\Controller\Controller::render() - CORE\src\Controller\Controller.php, line 611
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 120
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-11-11 03:42:10 Warning: Warning (2): Invalid argument supplied for foreach() in [C:\xampp\htdocs\cakephp\src\Template\Orders\index.ctp, line 13]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 138
include - APP/Template\Orders\index.ctp, line 13
Cake\View\View::_evaluate() - CORE\src\View\View.php, line 970
Cake\View\View::_render() - CORE\src\View\View.php, line 930
Cake\View\View::render() - CORE\src\View\View.php, line 578
Cake\Controller\Controller::render() - CORE\src\Controller\Controller.php, line 611
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 120
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-11-11 04:03:33 Error: [Cake\Database\Exception] SQLSTATE[42S02]: Base table or view not found: 1146 Table 'pizza.users' doesn't exist
Request URL: /cakephp/users/login
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Database\Schema\Collection.php(96): Cake\Database\Schema\Collection->_reflect('Column', 'users', Array, Object(Cake\Database\Schema\Table))
#1 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Database\Schema\CachedCollection.php(64): Cake\Database\Schema\Collection->describe('users', Array)
#2 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\ORM\Table.php(423): Cake\Database\Schema\CachedCollection->describe('users')
#3 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\ORM\Query.php(164): Cake\ORM\Table->schema()
#4 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\ORM\Query.php(122): Cake\ORM\Query->addDefaultTypes(Object(App\Model\Table\UsersTable))
#5 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\ORM\Table.php(1228): Cake\ORM\Query->__construct(Object(Cake\Database\Connection), Object(App\Model\Table\UsersTable))
#6 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\ORM\Table.php(931): Cake\ORM\Table->query()
#7 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Auth\BaseAuthenticate.php(147): Cake\ORM\Table->find('all', Array)
#8 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Auth\BaseAuthenticate.php(105): Cake\Auth\BaseAuthenticate->_query('root')
#9 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Auth\FormAuthenticate.php(77): Cake\Auth\BaseAuthenticate->_findUser('root', 'root')
#10 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Component\AuthComponent.php(764): Cake\Auth\FormAuthenticate->authenticate(Object(Cake\Network\Request), Object(Cake\Network\Response))
#11 C:\xampp\htdocs\cakephp\src\Controller\UsersController.php(18): Cake\Controller\Component\AuthComponent->identify()
#12 [internal function]: App\Controller\UsersController->login()
#13 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(429): call_user_func_array(Array, Array)
#14 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#15 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\UsersController))
#16 C:\xampp\htdocs\cakephp\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#17 {main}


2015-11-11 04:04:10 Error: Fatal Error (4): syntax error, unexpected 'if' (T_IF), expecting function (T_FUNCTION) in [C:\xampp\htdocs\cakephp\src\Controller\OrdersController.php, line 116]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-11-11 04:04:10 Error: [Cake\Error\FatalErrorException] syntax error, unexpected 'if' (T_IF), expecting function (T_FUNCTION)
Request URL: /cakephp/orders
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 116)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-11 05:00:56 Error: [Cake\View\Exception\MissingTemplateException] Template file "Users\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'Users\\index.ctp',
)
Request URL: /cakephp/users
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\View\View.php(575): Cake\View\View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(611): Cake\View\View->render(NULL, NULL)
#2 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(120): Cake\Controller\Controller->render()
#3 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\UsersController))
#4 C:\xampp\htdocs\cakephp\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#5 {main}


2015-11-11 05:03:16 Warning: Warning (2): Invalid argument supplied for foreach() in [C:\xampp\htdocs\cakephp\src\Controller\OrdersController.php, line 60]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 138
App\Controller\OrdersController::add() - APP/Controller\OrdersController.php, line 60
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 429
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 114
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-11-11 05:18:15 Error: Fatal Error (1): Call to a member function isOwnedBy() on boolean in [C:\xampp\htdocs\cakephp\src\Controller\OrdersController.php, line 119]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-11-11 05:18:15 Error: [Cake\Error\FatalErrorException] Call to a member function isOwnedBy() on boolean
Request URL: /cakephp/orders/edit/1
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 119)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-11 05:19:13 Error: [BadMethodCallException] Unknown method "isOwnedBy"
Request URL: /cakephp/orders/edit/1
Stack Trace:
#0 C:\xampp\htdocs\cakephp\src\Controller\OrdersController.php(120): Cake\ORM\Table->__call('isOwnedBy', Array)
#1 C:\xampp\htdocs\cakephp\src\Controller\OrdersController.php(120): Cake\ORM\Table->isOwnedBy(1, 1)
#2 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Auth\ControllerAuthorize.php(92): App\Controller\OrdersController->isAuthorized(Array)
#3 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Component\AuthComponent.php(494): Cake\Auth\ControllerAuthorize->authorize(Array, Object(Cake\Network\Request))
#4 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Component\AuthComponent.php(305): Cake\Controller\Component\AuthComponent->isAuthorized(Array)
#5 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Component\AuthComponent.php(258): Cake\Controller\Component\AuthComponent->authCheck(Object(Cake\Event\Event))
#6 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Event\EventManager.php(385): Cake\Controller\Component\AuthComponent->startup(Object(Cake\Event\Event))
#7 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Event\EventManager.php(355): Cake\Event\EventManager->_callListener(Array, Object(Cake\Event\Event))
#8 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Event\EventDispatcherTrait.php(78): Cake\Event\EventManager->dispatch(Object(Cake\Event\Event))
#9 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(495): Cake\Controller\Controller->dispatchEvent('Controller.star...')
#10 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(109): Cake\Controller\Controller->startupProcess()
#11 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\OrdersController))
#12 C:\xampp\htdocs\cakephp\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#13 {main}


2015-11-11 05:19:42 Error: [BadMethodCallException] Unknown method "isOwnedBy"
Request URL: /cakephp/orders/edit/1
Stack Trace:
#0 C:\xampp\htdocs\cakephp\src\Controller\OrdersController.php(120): Cake\ORM\Table->__call('isOwnedBy', Array)
#1 C:\xampp\htdocs\cakephp\src\Controller\OrdersController.php(120): Cake\ORM\Table->isOwnedBy(NULL, 1)
#2 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Auth\ControllerAuthorize.php(92): App\Controller\OrdersController->isAuthorized(Array)
#3 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Component\AuthComponent.php(494): Cake\Auth\ControllerAuthorize->authorize(Array, Object(Cake\Network\Request))
#4 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Component\AuthComponent.php(305): Cake\Controller\Component\AuthComponent->isAuthorized(Array)
#5 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Component\AuthComponent.php(258): Cake\Controller\Component\AuthComponent->authCheck(Object(Cake\Event\Event))
#6 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Event\EventManager.php(385): Cake\Controller\Component\AuthComponent->startup(Object(Cake\Event\Event))
#7 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Event\EventManager.php(355): Cake\Event\EventManager->_callListener(Array, Object(Cake\Event\Event))
#8 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Event\EventDispatcherTrait.php(78): Cake\Event\EventManager->dispatch(Object(Cake\Event\Event))
#9 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(495): Cake\Controller\Controller->dispatchEvent('Controller.star...')
#10 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(109): Cake\Controller\Controller->startupProcess()
#11 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\OrdersController))
#12 C:\xampp\htdocs\cakephp\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#13 {main}


2015-11-11 05:22:23 Error: Fatal Error (1): Call to a member function isOwnedBy() on boolean in [C:\xampp\htdocs\cakephp\src\Controller\OrdersController.php, line 120]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-11-11 05:22:23 Error: [Cake\Error\FatalErrorException] Call to a member function isOwnedBy() on boolean
Request URL: /cakephp/orders/edit/1
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 120)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-11 05:24:25 Error: Fatal Error (1): Call to a member function isOwnedBy() on boolean in [C:\xampp\htdocs\cakephp\src\Controller\OrdersController.php, line 120]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-11-11 05:24:26 Error: [Cake\Error\FatalErrorException] Call to a member function isOwnedBy() on boolean
Request URL: /cakephp/orders/edit/1
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 120)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-11 05:24:38 Error: [BadMethodCallException] Unknown method "isOwnedBy"
Request URL: /cakephp/orders/edit/1
Stack Trace:
#0 C:\xampp\htdocs\cakephp\src\Controller\OrdersController.php(120): Cake\ORM\Table->__call('isOwnedBy', Array)
#1 C:\xampp\htdocs\cakephp\src\Controller\OrdersController.php(120): Cake\ORM\Table->isOwnedBy(NULL, 1)
#2 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Auth\ControllerAuthorize.php(92): App\Controller\OrdersController->isAuthorized(Array)
#3 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Component\AuthComponent.php(494): Cake\Auth\ControllerAuthorize->authorize(Array, Object(Cake\Network\Request))
#4 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Component\AuthComponent.php(305): Cake\Controller\Component\AuthComponent->isAuthorized(Array)
#5 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Component\AuthComponent.php(258): Cake\Controller\Component\AuthComponent->authCheck(Object(Cake\Event\Event))
#6 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Event\EventManager.php(385): Cake\Controller\Component\AuthComponent->startup(Object(Cake\Event\Event))
#7 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Event\EventManager.php(355): Cake\Event\EventManager->_callListener(Array, Object(Cake\Event\Event))
#8 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Event\EventDispatcherTrait.php(78): Cake\Event\EventManager->dispatch(Object(Cake\Event\Event))
#9 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(495): Cake\Controller\Controller->dispatchEvent('Controller.star...')
#10 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(109): Cake\Controller\Controller->startupProcess()
#11 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\OrdersController))
#12 C:\xampp\htdocs\cakephp\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#13 {main}


2015-11-11 05:26:30 Error: [BadMethodCallException] Unknown method "isOwnedBy"
Request URL: /cakephp/orders/edit/1
Stack Trace:
#0 C:\xampp\htdocs\cakephp\src\Controller\OrdersController.php(120): Cake\ORM\Table->__call('isOwnedBy', Array)
#1 C:\xampp\htdocs\cakephp\src\Controller\OrdersController.php(120): Cake\ORM\Table->isOwnedBy(NULL, 1)
#2 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Auth\ControllerAuthorize.php(92): App\Controller\OrdersController->isAuthorized(Array)
#3 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Component\AuthComponent.php(494): Cake\Auth\ControllerAuthorize->authorize(Array, Object(Cake\Network\Request))
#4 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Component\AuthComponent.php(305): Cake\Controller\Component\AuthComponent->isAuthorized(Array)
#5 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Component\AuthComponent.php(258): Cake\Controller\Component\AuthComponent->authCheck(Object(Cake\Event\Event))
#6 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Event\EventManager.php(385): Cake\Controller\Component\AuthComponent->startup(Object(Cake\Event\Event))
#7 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Event\EventManager.php(355): Cake\Event\EventManager->_callListener(Array, Object(Cake\Event\Event))
#8 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Event\EventDispatcherTrait.php(78): Cake\Event\EventManager->dispatch(Object(Cake\Event\Event))
#9 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(495): Cake\Controller\Controller->dispatchEvent('Controller.star...')
#10 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(109): Cake\Controller\Controller->startupProcess()
#11 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\OrdersController))
#12 C:\xampp\htdocs\cakephp\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#13 {main}


2015-11-11 05:26:48 Error: [BadMethodCallException] Unknown method "isOwnedBy"
Request URL: /cakephp/orders/delete/0
Stack Trace:
#0 C:\xampp\htdocs\cakephp\src\Controller\OrdersController.php(120): Cake\ORM\Table->__call('isOwnedBy', Array)
#1 C:\xampp\htdocs\cakephp\src\Controller\OrdersController.php(120): Cake\ORM\Table->isOwnedBy(NULL, 1)
#2 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Auth\ControllerAuthorize.php(92): App\Controller\OrdersController->isAuthorized(Array)
#3 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Component\AuthComponent.php(494): Cake\Auth\ControllerAuthorize->authorize(Array, Object(Cake\Network\Request))
#4 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Component\AuthComponent.php(305): Cake\Controller\Component\AuthComponent->isAuthorized(Array)
#5 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Component\AuthComponent.php(258): Cake\Controller\Component\AuthComponent->authCheck(Object(Cake\Event\Event))
#6 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Event\EventManager.php(385): Cake\Controller\Component\AuthComponent->startup(Object(Cake\Event\Event))
#7 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Event\EventManager.php(355): Cake\Event\EventManager->_callListener(Array, Object(Cake\Event\Event))
#8 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Event\EventDispatcherTrait.php(78): Cake\Event\EventManager->dispatch(Object(Cake\Event\Event))
#9 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(495): Cake\Controller\Controller->dispatchEvent('Controller.star...')
#10 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(109): Cake\Controller\Controller->startupProcess()
#11 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\OrdersController))
#12 C:\xampp\htdocs\cakephp\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#13 {main}


2015-11-11 05:32:38 Error: Fatal Error (1): Call to a member function isOwnedBy() on boolean in [C:\xampp\htdocs\cakephp\src\Controller\OrdersController.php, line 120]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-11-11 05:32:39 Error: [Cake\Error\FatalErrorException] Call to a member function isOwnedBy() on boolean
Request URL: /cakephp/orders/edit/0
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 120)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-11 05:32:45 Error: Fatal Error (1): Call to a member function isOwnedBy() on boolean in [C:\xampp\htdocs\cakephp\src\Controller\OrdersController.php, line 120]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-11-11 05:32:45 Error: [Cake\Error\FatalErrorException] Call to a member function isOwnedBy() on boolean
Request URL: /cakephp/orders/delete/0
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 120)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-11 05:33:09 Error: Fatal Error (1): Call to a member function isOwnedBy() on boolean in [C:\xampp\htdocs\cakephp\src\Controller\OrdersController.php, line 120]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-11-11 05:33:09 Error: [Cake\Error\FatalErrorException] Call to a member function isOwnedBy() on boolean
Request URL: /cakephp/orders/edit/0
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 120)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-11 05:33:44 Error: [BadMethodCallException] Unknown method "isOwnedBy"
Request URL: /cakephp/orders/edit/0
Stack Trace:
#0 C:\xampp\htdocs\cakephp\src\Controller\OrdersController.php(120): Cake\ORM\Table->__call('isOwnedBy', Array)
#1 C:\xampp\htdocs\cakephp\src\Controller\OrdersController.php(120): Cake\ORM\Table->isOwnedBy(0, 1)
#2 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Auth\ControllerAuthorize.php(92): App\Controller\OrdersController->isAuthorized(Array)
#3 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Component\AuthComponent.php(494): Cake\Auth\ControllerAuthorize->authorize(Array, Object(Cake\Network\Request))
#4 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Component\AuthComponent.php(305): Cake\Controller\Component\AuthComponent->isAuthorized(Array)
#5 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Component\AuthComponent.php(258): Cake\Controller\Component\AuthComponent->authCheck(Object(Cake\Event\Event))
#6 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Event\EventManager.php(385): Cake\Controller\Component\AuthComponent->startup(Object(Cake\Event\Event))
#7 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Event\EventManager.php(355): Cake\Event\EventManager->_callListener(Array, Object(Cake\Event\Event))
#8 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Event\EventDispatcherTrait.php(78): Cake\Event\EventManager->dispatch(Object(Cake\Event\Event))
#9 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(495): Cake\Controller\Controller->dispatchEvent('Controller.star...')
#10 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(109): Cake\Controller\Controller->startupProcess()
#11 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\OrdersController))
#12 C:\xampp\htdocs\cakephp\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#13 {main}


2015-11-11 05:34:28 Error: Fatal Error (1): Call to a member function isOwnedBy() on boolean in [C:\xampp\htdocs\cakephp\src\Controller\OrdersController.php, line 120]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 90
[main] - [internal], line ??



2015-11-11 05:34:28 Error: [Cake\Error\FatalErrorException] Call to a member function isOwnedBy() on boolean
Request URL: /cakephp/orders/edit/0
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(90): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 120)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-11-11 05:34:38 Error: [BadMethodCallException] Unknown method "isOwnedBy"
Request URL: /cakephp/orders/edit/0
Stack Trace:
#0 C:\xampp\htdocs\cakephp\src\Controller\OrdersController.php(120): Cake\ORM\Table->__call('isOwnedBy', Array)
#1 C:\xampp\htdocs\cakephp\src\Controller\OrdersController.php(120): Cake\ORM\Table->isOwnedBy(0, 1)
#2 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Auth\ControllerAuthorize.php(92): App\Controller\OrdersController->isAuthorized(Array)
#3 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Component\AuthComponent.php(494): Cake\Auth\ControllerAuthorize->authorize(Array, Object(Cake\Network\Request))
#4 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Component\AuthComponent.php(305): Cake\Controller\Component\AuthComponent->isAuthorized(Array)
#5 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Component\AuthComponent.php(258): Cake\Controller\Component\AuthComponent->authCheck(Object(Cake\Event\Event))
#6 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Event\EventManager.php(385): Cake\Controller\Component\AuthComponent->startup(Object(Cake\Event\Event))
#7 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Event\EventManager.php(355): Cake\Event\EventManager->_callListener(Array, Object(Cake\Event\Event))
#8 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Event\EventDispatcherTrait.php(78): Cake\Event\EventManager->dispatch(Object(Cake\Event\Event))
#9 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(495): Cake\Controller\Controller->dispatchEvent('Controller.star...')
#10 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(109): Cake\Controller\Controller->startupProcess()
#11 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\OrdersController))
#12 C:\xampp\htdocs\cakephp\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#13 {main}


2015-11-11 05:37:02 Error: [BadMethodCallException] Unknown method "isOwnedBy"
Request URL: /cakephp/orders/edit/0
Stack Trace:
#0 C:\xampp\htdocs\cakephp\src\Controller\OrdersController.php(120): Cake\ORM\Table->__call('isOwnedBy', Array)
#1 C:\xampp\htdocs\cakephp\src\Controller\OrdersController.php(120): Cake\ORM\Table->isOwnedBy(0, 1)
#2 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Auth\ControllerAuthorize.php(92): App\Controller\OrdersController->isAuthorized(Array)
#3 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Component\AuthComponent.php(494): Cake\Auth\ControllerAuthorize->authorize(Array, Object(Cake\Network\Request))
#4 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Component\AuthComponent.php(305): Cake\Controller\Component\AuthComponent->isAuthorized(Array)
#5 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Component\AuthComponent.php(258): Cake\Controller\Component\AuthComponent->authCheck(Object(Cake\Event\Event))
#6 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Event\EventManager.php(385): Cake\Controller\Component\AuthComponent->startup(Object(Cake\Event\Event))
#7 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Event\EventManager.php(355): Cake\Event\EventManager->_callListener(Array, Object(Cake\Event\Event))
#8 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Event\EventDispatcherTrait.php(78): Cake\Event\EventManager->dispatch(Object(Cake\Event\Event))
#9 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(495): Cake\Controller\Controller->dispatchEvent('Controller.star...')
#10 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(109): Cake\Controller\Controller->startupProcess()
#11 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\OrdersController))
#12 C:\xampp\htdocs\cakephp\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#13 {main}


2015-11-11 14:41:38 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY'
Request URL: /cakephp/orders/add
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Database\Statement\MysqlStatement.php(36): PDOStatement->execute(NULL)
#1 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Database\Statement\StatementDecorator.php(171): Cake\Database\Statement\MysqlStatement->execute(NULL)
#2 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Database\Log\LoggingStatement.php(56): Cake\Database\Statement\StatementDecorator->execute(NULL)
#3 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Database\Connection.php(270): Cake\Database\Log\LoggingStatement->execute()
#4 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Database\Query.php(174): Cake\Database\Connection->run(Object(Cake\ORM\Query))
#5 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\ORM\Table.php(1530): Cake\Database\Query->execute()
#6 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\ORM\Table.php(1446): Cake\ORM\Table->_insert(Object(Cake\ORM\Entity), Array)
#7 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\ORM\Table.php(1377): Cake\ORM\Table->_processSave(Object(Cake\ORM\Entity), Object(ArrayObject))
#8 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Database\Connection.php(557): Cake\ORM\Table->Cake\ORM\{closure}(Object(Cake\Database\Connection))
#9 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\ORM\Table.php(1378): Cake\Database\Connection->transactional(Object(Closure))
#10 C:\xampp\htdocs\cakephp\src\Controller\OrdersController.php(74): Cake\ORM\Table->save(Object(Cake\ORM\Entity))
#11 [internal function]: App\Controller\OrdersController->add()
#12 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(429): call_user_func_array(Array, Array)
#13 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#14 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\OrdersController))
#15 C:\xampp\htdocs\cakephp\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#16 {main}


2015-11-11 14:42:36 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY'
Request URL: /cakephp/orders/add
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Database\Statement\MysqlStatement.php(36): PDOStatement->execute(NULL)
#1 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Database\Statement\StatementDecorator.php(171): Cake\Database\Statement\MysqlStatement->execute(NULL)
#2 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Database\Log\LoggingStatement.php(56): Cake\Database\Statement\StatementDecorator->execute(NULL)
#3 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Database\Connection.php(270): Cake\Database\Log\LoggingStatement->execute()
#4 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Database\Query.php(174): Cake\Database\Connection->run(Object(Cake\ORM\Query))
#5 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\ORM\Table.php(1530): Cake\Database\Query->execute()
#6 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\ORM\Table.php(1446): Cake\ORM\Table->_insert(Object(Cake\ORM\Entity), Array)
#7 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\ORM\Table.php(1377): Cake\ORM\Table->_processSave(Object(Cake\ORM\Entity), Object(ArrayObject))
#8 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Database\Connection.php(557): Cake\ORM\Table->Cake\ORM\{closure}(Object(Cake\Database\Connection))
#9 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\ORM\Table.php(1378): Cake\Database\Connection->transactional(Object(Closure))
#10 C:\xampp\htdocs\cakephp\src\Controller\OrdersController.php(74): Cake\ORM\Table->save(Object(Cake\ORM\Entity))
#11 [internal function]: App\Controller\OrdersController->add()
#12 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(429): call_user_func_array(Array, Array)
#13 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#14 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\OrdersController))
#15 C:\xampp\htdocs\cakephp\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#16 {main}


2015-11-11 14:44:11 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY'
Request URL: /cakephp/orders/add
Stack Trace:
#0 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Database\Statement\MysqlStatement.php(36): PDOStatement->execute(NULL)
#1 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Database\Statement\StatementDecorator.php(171): Cake\Database\Statement\MysqlStatement->execute(NULL)
#2 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Database\Log\LoggingStatement.php(56): Cake\Database\Statement\StatementDecorator->execute(NULL)
#3 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Database\Connection.php(270): Cake\Database\Log\LoggingStatement->execute()
#4 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Database\Query.php(174): Cake\Database\Connection->run(Object(Cake\ORM\Query))
#5 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\ORM\Table.php(1530): Cake\Database\Query->execute()
#6 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\ORM\Table.php(1446): Cake\ORM\Table->_insert(Object(Cake\ORM\Entity), Array)
#7 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\ORM\Table.php(1377): Cake\ORM\Table->_processSave(Object(Cake\ORM\Entity), Object(ArrayObject))
#8 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Database\Connection.php(557): Cake\ORM\Table->Cake\ORM\{closure}(Object(Cake\Database\Connection))
#9 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\ORM\Table.php(1378): Cake\Database\Connection->transactional(Object(Closure))
#10 C:\xampp\htdocs\cakephp\src\Controller\OrdersController.php(74): Cake\ORM\Table->save(Object(Cake\ORM\Entity))
#11 [internal function]: App\Controller\OrdersController->add()
#12 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(429): call_user_func_array(Array, Array)
#13 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#14 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\OrdersController))
#15 C:\xampp\htdocs\cakephp\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#16 {main}


2015-11-11 14:48:50 Error: [BadMethodCallException] Unknown method "isOwnedBy"
Request URL: /cakephp/orders/delete/1
Stack Trace:
#0 C:\xampp\htdocs\cakephp\src\Controller\OrdersController.php(120): Cake\ORM\Table->__call('isOwnedBy', Array)
#1 C:\xampp\htdocs\cakephp\src\Controller\OrdersController.php(120): Cake\ORM\Table->isOwnedBy(1, 1)
#2 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Auth\ControllerAuthorize.php(92): App\Controller\OrdersController->isAuthorized(Array)
#3 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Component\AuthComponent.php(494): Cake\Auth\ControllerAuthorize->authorize(Array, Object(Cake\Network\Request))
#4 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Component\AuthComponent.php(305): Cake\Controller\Component\AuthComponent->isAuthorized(Array)
#5 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Component\AuthComponent.php(258): Cake\Controller\Component\AuthComponent->authCheck(Object(Cake\Event\Event))
#6 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Event\EventManager.php(385): Cake\Controller\Component\AuthComponent->startup(Object(Cake\Event\Event))
#7 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Event\EventManager.php(355): Cake\Event\EventManager->_callListener(Array, Object(Cake\Event\Event))
#8 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Event\EventDispatcherTrait.php(78): Cake\Event\EventManager->dispatch(Object(Cake\Event\Event))
#9 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(495): Cake\Controller\Controller->dispatchEvent('Controller.star...')
#10 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(109): Cake\Controller\Controller->startupProcess()
#11 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\OrdersController))
#12 C:\xampp\htdocs\cakephp\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#13 {main}


2015-11-11 14:49:09 Error: [BadMethodCallException] Unknown method "isOwnedBy"
Request URL: /cakephp/orders/edit/1
Stack Trace:
#0 C:\xampp\htdocs\cakephp\src\Controller\OrdersController.php(120): Cake\ORM\Table->__call('isOwnedBy', Array)
#1 C:\xampp\htdocs\cakephp\src\Controller\OrdersController.php(120): Cake\ORM\Table->isOwnedBy(1, 1)
#2 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Auth\ControllerAuthorize.php(92): App\Controller\OrdersController->isAuthorized(Array)
#3 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Component\AuthComponent.php(494): Cake\Auth\ControllerAuthorize->authorize(Array, Object(Cake\Network\Request))
#4 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Component\AuthComponent.php(305): Cake\Controller\Component\AuthComponent->isAuthorized(Array)
#5 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Component\AuthComponent.php(258): Cake\Controller\Component\AuthComponent->authCheck(Object(Cake\Event\Event))
#6 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Event\EventManager.php(385): Cake\Controller\Component\AuthComponent->startup(Object(Cake\Event\Event))
#7 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Event\EventManager.php(355): Cake\Event\EventManager->_callListener(Array, Object(Cake\Event\Event))
#8 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Event\EventDispatcherTrait.php(78): Cake\Event\EventManager->dispatch(Object(Cake\Event\Event))
#9 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(495): Cake\Controller\Controller->dispatchEvent('Controller.star...')
#10 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(109): Cake\Controller\Controller->startupProcess()
#11 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\OrdersController))
#12 C:\xampp\htdocs\cakephp\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#13 {main}


2015-11-11 14:49:09 Error: [BadMethodCallException] Unknown method "isOwnedBy"
Request URL: /cakephp/orders/edit/1
Stack Trace:
#0 C:\xampp\htdocs\cakephp\src\Controller\OrdersController.php(120): Cake\ORM\Table->__call('isOwnedBy', Array)
#1 C:\xampp\htdocs\cakephp\src\Controller\OrdersController.php(120): Cake\ORM\Table->isOwnedBy(1, 1)
#2 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Auth\ControllerAuthorize.php(92): App\Controller\OrdersController->isAuthorized(Array)
#3 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Component\AuthComponent.php(494): Cake\Auth\ControllerAuthorize->authorize(Array, Object(Cake\Network\Request))
#4 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Component\AuthComponent.php(305): Cake\Controller\Component\AuthComponent->isAuthorized(Array)
#5 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Component\AuthComponent.php(258): Cake\Controller\Component\AuthComponent->authCheck(Object(Cake\Event\Event))
#6 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Event\EventManager.php(385): Cake\Controller\Component\AuthComponent->startup(Object(Cake\Event\Event))
#7 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Event\EventManager.php(355): Cake\Event\EventManager->_callListener(Array, Object(Cake\Event\Event))
#8 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Event\EventDispatcherTrait.php(78): Cake\Event\EventManager->dispatch(Object(Cake\Event\Event))
#9 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(495): Cake\Controller\Controller->dispatchEvent('Controller.star...')
#10 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(109): Cake\Controller\Controller->startupProcess()
#11 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\OrdersController))
#12 C:\xampp\htdocs\cakephp\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#13 {main}


2015-11-11 14:49:55 Error: [BadMethodCallException] Unknown method "isOwnedBy"
Request URL: /cakephp/orders/edit/1
Stack Trace:
#0 C:\xampp\htdocs\cakephp\src\Controller\OrdersController.php(120): Cake\ORM\Table->__call('isOwnedBy', Array)
#1 C:\xampp\htdocs\cakephp\src\Controller\OrdersController.php(120): Cake\ORM\Table->isOwnedBy(1, 1)
#2 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Auth\ControllerAuthorize.php(92): App\Controller\OrdersController->isAuthorized(Array)
#3 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Component\AuthComponent.php(494): Cake\Auth\ControllerAuthorize->authorize(Array, Object(Cake\Network\Request))
#4 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Component\AuthComponent.php(305): Cake\Controller\Component\AuthComponent->isAuthorized(Array)
#5 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Component\AuthComponent.php(258): Cake\Controller\Component\AuthComponent->authCheck(Object(Cake\Event\Event))
#6 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Event\EventManager.php(385): Cake\Controller\Component\AuthComponent->startup(Object(Cake\Event\Event))
#7 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Event\EventManager.php(355): Cake\Event\EventManager->_callListener(Array, Object(Cake\Event\Event))
#8 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Event\EventDispatcherTrait.php(78): Cake\Event\EventManager->dispatch(Object(Cake\Event\Event))
#9 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(495): Cake\Controller\Controller->dispatchEvent('Controller.star...')
#10 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(109): Cake\Controller\Controller->startupProcess()
#11 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\OrdersController))
#12 C:\xampp\htdocs\cakephp\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#13 {main}


2015-11-11 14:51:08 Error: [BadMethodCallException] Unknown method "isOwnedBy"
Request URL: /cakephp/orders/edit/1
Stack Trace:
#0 C:\xampp\htdocs\cakephp\src\Controller\OrdersController.php(120): Cake\ORM\Table->__call('isOwnedBy', Array)
#1 C:\xampp\htdocs\cakephp\src\Controller\OrdersController.php(120): Cake\ORM\Table->isOwnedBy(1, 1)
#2 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Auth\ControllerAuthorize.php(92): App\Controller\OrdersController->isAuthorized(Array)
#3 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Component\AuthComponent.php(494): Cake\Auth\ControllerAuthorize->authorize(Array, Object(Cake\Network\Request))
#4 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Component\AuthComponent.php(305): Cake\Controller\Component\AuthComponent->isAuthorized(Array)
#5 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Component\AuthComponent.php(258): Cake\Controller\Component\AuthComponent->authCheck(Object(Cake\Event\Event))
#6 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Event\EventManager.php(385): Cake\Controller\Component\AuthComponent->startup(Object(Cake\Event\Event))
#7 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Event\EventManager.php(355): Cake\Event\EventManager->_callListener(Array, Object(Cake\Event\Event))
#8 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Event\EventDispatcherTrait.php(78): Cake\Event\EventManager->dispatch(Object(Cake\Event\Event))
#9 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(495): Cake\Controller\Controller->dispatchEvent('Controller.star...')
#10 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(109): Cake\Controller\Controller->startupProcess()
#11 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\OrdersController))
#12 C:\xampp\htdocs\cakephp\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#13 {main}


2015-11-11 14:52:57 Error: [BadMethodCallException] Unknown method "isOwnedBy"
Request URL: /cakephp/orders/edit/1
Stack Trace:
#0 C:\xampp\htdocs\cakephp\src\Controller\OrdersController.php(118): Cake\ORM\Table->__call('isOwnedBy', Array)
#1 C:\xampp\htdocs\cakephp\src\Controller\OrdersController.php(118): Cake\ORM\Table->isOwnedBy(1, 1)
#2 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Auth\ControllerAuthorize.php(92): App\Controller\OrdersController->isAuthorized(Array)
#3 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Component\AuthComponent.php(494): Cake\Auth\ControllerAuthorize->authorize(Array, Object(Cake\Network\Request))
#4 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Component\AuthComponent.php(305): Cake\Controller\Component\AuthComponent->isAuthorized(Array)
#5 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Component\AuthComponent.php(258): Cake\Controller\Component\AuthComponent->authCheck(Object(Cake\Event\Event))
#6 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Event\EventManager.php(385): Cake\Controller\Component\AuthComponent->startup(Object(Cake\Event\Event))
#7 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Event\EventManager.php(355): Cake\Event\EventManager->_callListener(Array, Object(Cake\Event\Event))
#8 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Event\EventDispatcherTrait.php(78): Cake\Event\EventManager->dispatch(Object(Cake\Event\Event))
#9 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(495): Cake\Controller\Controller->dispatchEvent('Controller.star...')
#10 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(109): Cake\Controller\Controller->startupProcess()
#11 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\OrdersController))
#12 C:\xampp\htdocs\cakephp\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#13 {main}


2015-11-11 14:53:04 Error: [BadMethodCallException] Unknown method "isOwnedBy"
Request URL: /cakephp/orders/delete/1
Stack Trace:
#0 C:\xampp\htdocs\cakephp\src\Controller\OrdersController.php(118): Cake\ORM\Table->__call('isOwnedBy', Array)
#1 C:\xampp\htdocs\cakephp\src\Controller\OrdersController.php(118): Cake\ORM\Table->isOwnedBy(1, 1)
#2 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Auth\ControllerAuthorize.php(92): App\Controller\OrdersController->isAuthorized(Array)
#3 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Component\AuthComponent.php(494): Cake\Auth\ControllerAuthorize->authorize(Array, Object(Cake\Network\Request))
#4 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Component\AuthComponent.php(305): Cake\Controller\Component\AuthComponent->isAuthorized(Array)
#5 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Component\AuthComponent.php(258): Cake\Controller\Component\AuthComponent->authCheck(Object(Cake\Event\Event))
#6 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Event\EventManager.php(385): Cake\Controller\Component\AuthComponent->startup(Object(Cake\Event\Event))
#7 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Event\EventManager.php(355): Cake\Event\EventManager->_callListener(Array, Object(Cake\Event\Event))
#8 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Event\EventDispatcherTrait.php(78): Cake\Event\EventManager->dispatch(Object(Cake\Event\Event))
#9 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(495): Cake\Controller\Controller->dispatchEvent('Controller.star...')
#10 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(109): Cake\Controller\Controller->startupProcess()
#11 C:\xampp\htdocs\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\OrdersController))
#12 C:\xampp\htdocs\cakephp\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#13 {main}


